// Comprehensive MBTI personality type descriptions for Crossd dating app
export const MBTI_FULL_DESCRIPTIONS = {
  'INTJ': {
    emoji: '🏛️',
    title: 'The Mastermind / Architect',
    keyTraits: ['Strategic', 'Independent', 'Visionary', 'Logical'],
    strengths: ['Long-term planning', 'Self-motivated', 'Logical problem solving', 'Innovation'],
    weaknesses: ['Dismissive of emotions', 'Perfectionistic', 'Aloof', 'Overly critical'],
    idealRoles: ['Architect', 'Scientist', 'Entrepreneur', 'Strategist'],
    relationshipApproach: "Architects approach relationships with the same strategic mindset they apply to everything else. They value partners who can match their intellect and ambition while respecting their need for independence. They show love through meaningful actions and shared future-building.",
    communication: "Direct and efficient communicators. Prefer deep, intellectual conversations over small talk. May need to consciously express emotions.",
    compatibility: "Best with types who offer emotional warmth while respecting independence: ENFP, ENTP, INFJ",
    famousExamples: ['Elon Musk', 'Friedrich Nietzsche', 'Michelle Obama', 'Christopher Nolan']
  },
  'INTP': {
    emoji: '🧪',
    title: 'The Thinker / Logician',
    keyTraits: ['Analytical', 'Curious', 'Abstract thinker', 'Innovative'],
    strengths: ['Idea generation', 'Innovation', 'Objectivity', 'Pattern recognition'],
    weaknesses: ['Poor with follow-through', 'Socially distant', 'Indecisive', 'Absent-minded'],
    idealRoles: ['Researcher', 'Developer', 'Philosopher', 'Systems analyst'],
    relationshipApproach: "In relationships, Logicians value intellectual connection above all. They show affection through shared ideas and problem-solving rather than overt emotional displays, and they need a partner who respects their independence and thirst for solitude.",
    communication: "Dry humor, wordplay, and debates. May forget to express affection explicitly. Prefer 1:1 deep conversations.",
    compatibility: "Best with types who offer grounding and warmth: ENFJ, INFJ, ENFP, INFP",
    famousExamples: ['Albert Einstein', 'Bill Gates', 'Isaac Newton', 'Stanley Kubrick']
  },
  'ENTJ': {
    emoji: '👑',
    title: 'The Commander / Executive',
    keyTraits: ['Bold', 'Decisive', 'Efficient leader', 'Strategic'],
    strengths: ['Leadership', 'Strategy', 'Drive for achievement', 'Confidence'],
    weaknesses: ['May steamroll others', 'Impatient', 'Neglect emotional nuance', 'Domineering'],
    idealRoles: ['CEO', 'Executive', 'Project leader', 'Military officer'],
    relationshipApproach: "Commanders seek partners who can keep up with their ambitious nature. They value efficiency and directness in relationships and show love through acts of service and achieving shared goals. They need someone who won't be intimidated by their intensity.",
    communication: "Direct, assertive, and goal-oriented. Appreciate intellectual challenges but may need to soften delivery.",
    compatibility: "Best with types who can match their intensity: INTP, INTJ, INFP, ENFP",
    famousExamples: ['Steve Jobs', 'Margaret Thatcher', 'Napoleon Bonaparte', 'Gordon Ramsay']
  },
  'ENTP': {
    emoji: '💡',
    title: 'The Debater / Visionary',
    keyTraits: ['Energetic', 'Witty', 'Idea-driven', 'Innovative'],
    strengths: ['Debate', 'Improvisation', 'Spotting opportunities', 'Charisma'],
    weaknesses: ['Easily bored', 'Argumentative', 'Distractible', 'Insensitive'],
    idealRoles: ['Entrepreneur', 'Marketer', 'Inventor', 'Media personality'],
    relationshipApproach: "Debaters thrive on intellectual sparring and mental stimulation in relationships. They need partners who can engage in debates without taking things personally and who appreciate their playful nature. They show love through witty banter and shared adventures.",
    communication: "Playful, provocative, loves intellectual debate. May challenge partners to keep things interesting.",
    compatibility: "Best with deep thinkers who can keep up: INFJ, INTJ, ENFJ, INFP",
    famousExamples: ['Mark Twain', 'Adam Savage', 'Sarah Silverman', 'Leonardo da Vinci']
  },
  'INFJ': {
    emoji: '🌟',
    title: 'The Advocate / Counselor',
    keyTraits: ['Quietly visionary', 'Idealistic', 'Emotionally intelligent', 'Insightful'],
    strengths: ['Deep insight', 'Loyalty', 'Purposeful planning', 'Empathy'],
    weaknesses: ['Overthinker', 'Burnout-prone', 'Too idealistic', 'Perfectionistic'],
    idealRoles: ['Therapist', 'Writer', 'Coach', 'Spiritual leader'],
    relationshipApproach: "Advocates seek deep, meaningful connections and are intensely devoted partners. They need someone who can appreciate their idealism and provide emotional reciprocity in the relationship. They express love through understanding and supporting their partner's growth.",
    communication: "Deep, meaningful conversations. Excellent listeners who remember details. May need alone time to recharge.",
    compatibility: "Best with energetic types who appreciate depth: ENTP, ENFP, INFP, ENFJ",
    famousExamples: ['Martin Luther King Jr.', 'Nelson Mandela', 'Lady Gaga', 'Plato']
  },
  'INFP': {
    emoji: '🎨',
    title: 'The Mediator / Idealist',
    keyTraits: ['Gentle', 'Introspective', 'Values-driven', 'Creative'],
    strengths: ['Creativity', 'Authenticity', 'Empathy', 'Open-mindedness'],
    weaknesses: ['Conflict avoidant', 'Disorganized', 'Sensitive', 'Unrealistic'],
    idealRoles: ['Poet', 'Counselor', 'Storyteller', 'Humanitarian'],
    relationshipApproach: "Mediators are hopeless romantics who seek authentic, soulful connections. They express love through creative gestures and need partners who can appreciate their emotional depth and idealistic nature. They value authenticity above all else.",
    communication: "Gentle, thoughtful, poetic. Prefer meaningful one-on-one time. May struggle with direct conflict.",
    compatibility: "Best with decisive types who appreciate their sensitivity: ENFJ, ENTJ, INFJ, ENFP",
    famousExamples: ['William Shakespeare', 'Vincent van Gogh', 'Audrey Hepburn', 'Johnny Depp']
  },
  'ENFJ': {
    emoji: '✨',
    title: 'The Protagonist / Teacher',
    keyTraits: ['Charismatic', 'Supportive', 'Organized', 'Inspiring'],
    strengths: ['Motivation', 'Leadership', 'Emotional attunement', 'Communication'],
    weaknesses: ['May neglect self-needs', 'Overly idealistic', 'Sensitive to criticism', 'Controlling'],
    idealRoles: ['Teacher', 'Public speaker', 'Mentor', 'Campaigner'],
    relationshipApproach: "Protagonists are warm and affirming partners who prioritize their loved one's growth. They show love through encouragement and support, and need partners who can reciprocate their emotional investment while reminding them to care for themselves.",
    communication: "Warm, expressive, naturally encouraging. Skilled at reading others' emotions and creating harmony.",
    compatibility: "Best with introspective types who need their warmth: INFP, ISFP, INTP, ENFP",
    famousExamples: ['Barack Obama', 'Oprah Winfrey', 'Maya Angelou', 'Jennifer Lawrence']
  },
  'ENFP': {
    emoji: '🎉',
    title: 'The Campaigner / Inspirer',
    keyTraits: ['Enthusiastic', 'Creative', 'People-centered', 'Spontaneous'],
    strengths: ['Energy', 'Spontaneity', 'Emotional insight', 'Optimism'],
    weaknesses: ['Scattered', 'Overcommitted', 'Easily distracted', 'Struggle with routine'],
    idealRoles: ['Actor', 'Coach', 'Creative director', 'Startup founder'],
    relationshipApproach: "Campaigners bring energy and warmth to relationships, constantly seeking new experiences with their partners. They need someone who can match their enthusiasm while providing gentle grounding. They show love through excitement and constant reinvention.",
    communication: "Expressive, enthusiastic, full of possibilities. Love deep conversations about meaning and potential.",
    compatibility: "Best with grounded types who can channel their energy: INTJ, INFJ, ENTJ, ENFJ",
    famousExamples: ['Robin Williams', 'Ellen DeGeneres', 'Quentin Tarantino', 'Walt Disney']
  },
  'ISTJ': {
    emoji: '📋',
    title: 'The Inspector / Logistician',
    keyTraits: ['Responsible', 'Loyal', 'Detail-focused', 'Traditional'],
    strengths: ['Consistency', 'Duty', 'Factual memory', 'Reliability'],
    weaknesses: ['Rigid', 'Uncomfortable with change', 'Judgmental', 'Insensitive'],
    idealRoles: ['Accountant', 'Analyst', 'Military officer', 'Engineer'],
    relationshipApproach: "Logisticians show love through loyalty and dependability. They value tradition and stability in relationships and express affection through practical acts of service rather than grand romantic gestures. They need partners who appreciate their reliability.",
    communication: "Direct, factual, prefers clear expectations. May struggle with expressing emotions openly.",
    compatibility: "Best with flexible types who appreciate structure: ESTP, ESFP, ESTJ, ISFJ",
    famousExamples: ['George Washington', 'Warren Buffett', 'Angela Merkel', 'Denzel Washington']
  },
  'ISFJ': {
    emoji: '🛡️',
    title: 'The Defender / Nurturer',
    keyTraits: ['Kind', 'Service-oriented', 'Dependable', 'Traditional'],
    strengths: ['Supportive', 'Patient', 'Practical', 'Observant'],
    weaknesses: ['Avoids conflict', 'Underestimates self', 'Reluctant to change', 'Too selfless'],
    idealRoles: ['Nurse', 'Caregiver', 'Librarian', 'Administrator'],
    relationshipApproach: "Defenders are devoted and attentive partners who remember small details that matter. They need partners who appreciate their selfless nature and can encourage them to prioritize their own needs. They show love through acts of service.",
    communication: "Warm, considerate, excellent listeners. May avoid expressing own needs to keep peace.",
    compatibility: "Best with adventurous types who appreciate their care: ESFP, ESTP, ISFP, ISTJ",
    famousExamples: ['Mother Teresa', 'Queen Elizabeth II', 'Kate Middleton', 'Beyoncé']
  },
  'ESTJ': {
    emoji: '⚖️',
    title: 'The Executive / Director',
    keyTraits: ['Organized', 'Dedicated', 'Honest', 'Traditional'],
    strengths: ['Leadership', 'Direct', 'Loyal', 'Practical'],
    weaknesses: ['Inflexible', 'Uncomfortable with emotion', 'Judgmental', 'Difficulty relaxing'],
    idealRoles: ['Manager', 'Judge', 'Police officer', 'Business administrator'],
    relationshipApproach: "Executives approach relationships with the same dedication they bring to everything else. They value honesty and commitment, and show love through creating stability and security for their partners. They need someone who respects traditions.",
    communication: "Direct, organized, values structure. May need to consciously soften approach with emotions.",
    compatibility: "Best with adaptable types who value stability: ISTP, ISFP, ISTJ, ESFJ",
    famousExamples: ['John D. Rockefeller', 'Sonia Sotomayor', 'Lyndon B. Johnson', 'Judge Judy']
  },
  'ESFJ': {
    emoji: '🤗',
    title: 'The Consul / Provider',
    keyTraits: ['Warm', 'Social', 'Attentive to others needs', 'Organized'],
    strengths: ['Harmony', 'Community building', 'Reliability', 'Practical skills'],
    weaknesses: ['Approval-seeking', 'Avoid confrontation', 'Inflexible', 'Too selfless'],
    idealRoles: ['HR', 'Host', 'Teacher', 'Customer support lead'],
    relationshipApproach: "Consuls are warm and nurturing partners who excel at creating harmonious relationships. They show love through caring gestures and need partners who can express appreciation and reciprocate their affection. They value loyalty and commitment.",
    communication: "Friendly, supportive, socially aware. Love planning events and bringing people together.",
    compatibility: "Best with independent types who value their care: ISFP, ISTP, ISTJ, ESTJ",
    famousExamples: ['Taylor Swift', 'Danny Glover', 'Jennifer Garner', 'Terry Bradshaw']
  },
  'ISTP': {
    emoji: '🔧',
    title: 'The Virtuoso / Craftsman',
    keyTraits: ['Independent', 'Resourceful', 'Hands-on', 'Practical'],
    strengths: ['Technical skill', 'Calm in crisis', 'Logical problem solving', 'Flexibility'],
    weaknesses: ['Private', 'Unpredictable', 'Emotionally detached', 'Risk-prone'],
    idealRoles: ['Engineer', 'Mechanic', 'Survivalist', 'Stunt coordinator'],
    relationshipApproach: "Virtuosos need space and freedom in relationships. They show affection through actions rather than words and need partners who can respect their independence while sharing in hands-on adventures. They value authenticity.",
    communication: "Actions speak louder than words. Reserved but witty when comfortable. Need personal space.",
    compatibility: "Best with organized types who appreciate their skills: ESTJ, ESFJ, ESTP, ISTJ",
    famousExamples: ['Clint Eastwood', 'Bear Grylls', 'Tom Cruise', 'Olivia Wilde']
  },
  'ISFP': {
    emoji: '🎨',
    title: 'The Adventurer / Composer',
    keyTraits: ['Artistic', 'Free-spirited', 'Sensitive', 'Spontaneous'],
    strengths: ['Creativity', 'Gentle authenticity', 'Aesthetic appreciation', 'Flexibility'],
    weaknesses: ['Easily hurt', 'Dislikes structure', 'Avoids confrontation', 'Unpredictable'],
    idealRoles: ['Designer', 'Artist', 'Musician', 'Animal caretaker'],
    relationshipApproach: "Adventurers are spontaneous and creative partners who live in the moment. They express love through thoughtful gestures and experiences, and need partners who appreciate their free-spirited nature while providing gentle stability.",
    communication: "Gentle, artistic, expressive through actions. May struggle with verbalizing feelings directly.",
    compatibility: "Best with structured types who appreciate their creativity: ESFJ, ENFJ, ESTJ, ISFJ",
    famousExamples: ['Michael Jackson', 'Britney Spears', 'Lana Del Rey', 'Kevin Costner']
  },
  'ESTP': {
    emoji: '🚀',
    title: 'The Entrepreneur / Dynamo',
    keyTraits: ['Bold', 'Perceptive', 'Direct', 'Energetic'],
    strengths: ['Action-oriented', 'Adaptable', 'Sociable', 'Rational'],
    weaknesses: ['Impatient', 'Risk-prone', 'Unstructured', 'Insensitive'],
    idealRoles: ['Sales', 'Paramedic', 'Athlete', 'Stock trader'],
    relationshipApproach: "Entrepreneurs bring excitement and energy to relationships. They live for action and adventure, and need partners who can keep up with their fast-paced lifestyle and appreciate their spontaneity. They show love through shared experiences.",
    communication: "Direct, witty, action-focused. Prefer doing over talking. May be blunt but honest.",
    compatibility: "Best with calm types who enjoy their energy: ISFJ, ISTJ, ESFP, ISTP",
    famousExamples: ['Madonna', 'Ernest Hemingway', 'Eddie Murphy', 'Bruce Willis']
  },
  'ESFP': {
    emoji: '🌈',
    title: 'The Performer / Entertainer',
    keyTraits: ['Fun-loving', 'Spontaneous', 'Charming', 'Present-focused'],
    strengths: ['Social magnetism', 'Present-moment focus', 'Practical help', 'Enthusiasm'],
    weaknesses: ['Dislike of routine', 'Ignore deeper issues', 'Sensitive', 'Easily bored'],
    idealRoles: ['Actor', 'Event planner', 'Performer', 'Hospitality expert'],
    relationshipApproach: "Entertainers are fun-loving and affectionate partners who excel at making others feel special. They show love through creating joyful experiences and need partners who can appreciate their vibrant energy while providing occasional grounding.",
    communication: "Expressive, entertaining, socially skilled. Love being the life of the party and making others smile.",
    compatibility: "Best with stable types who appreciate fun: ISTJ, ISFJ, ESTP, ENFP",
    famousExamples: ['Marilyn Monroe', 'Jamie Oliver', 'Adele', 'Elvis Presley']
  }
};